[package]
name = "buildshd"
version = "0.1.0"
authors = ["Travis CI Humans <support+buildshd@travis-ci.com>"]
edition = "2018"

[dependencies]
quicli = "0.4"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
